### ISSUE TITLE
Extend changes order of yaml

### ISSUE THREAD

**Issue by infused-kim** [ergogen/ergogen#100]
I noticed a problem with the extend preprocessor function. It moves the extended yaml objects to the top of the yaml section.

For example:
```yaml
settings:
  preset_points:
    $extends: presets.kim.points

presets:
  kim:
    points:
      edge_thumb_cluster_top.anchor.shift: [10, 10]

units:


points:
  zones:
    $extends: settings.preset_points
    #
    # Thumb Cluster
    #
    thumbs:
      anchor:
        shift: [100, -100]
      columns:
        inner:
            key:
              column_net: C5
      rows:
        cluster:
          row_net: R4
    #
    # Helper Points
    #
    edge_thumb_cluster_top:
      anchor:
        ref: thumbs_inner_cluster
        shift: [0, 0]
      key:
        name: edge_thumb_cluster_top
```

If you run ergogen against it, you will get the following error:
```shell
❯ ergogen ./debug -o ./debug/output -d
Ergogen v4.0.4 CLI (Debug Mode)

Analyzing folder...
Interpreting format: YAML
Preprocessing input...
Calculating variables...
Parsing points...
Error: Unknown point reference "thumbs_inner_cluster" in anchor "points.zones.edge_thumb_cluster_top.anchor"!
    at exports.assert (/opt/homebrew/lib/node_modules/ergogen/src/assert.js:12:15)
    at /opt/homebrew/lib/node_modules/ergogen/src/anchor.js:69:15
    at exports.parse (/opt/homebrew/lib/node_modules/ergogen/src/points.js:294:103)
    at Object.process (/opt/homebrew/lib/node_modules/ergogen/src/ergogen.js:55:31)
    at /opt/homebrew/lib/node_modules/ergogen/src/cli.js:127:29
```

You can output the preprocessed config by adding the following lines to ergogen.js:

At the top:
```js
const yaml = require('js-yaml')
```

And around line 31:
```js
    if (debug) {
        logger(`After preprocess: ${yaml.safeDump(results.canonical)}`)
    }
```

You will see:
```yaml
  preset_points:
    edge_thumb_cluster_top:
      anchor:
        shift:
          - 10
          - 10
presets:
  kim:
    points:
      edge_thumb_cluster_top:
        anchor:
          shift:
            - 10
            - 10
units: null
points:
  zones:
    edge_thumb_cluster_top:
      anchor:
        shift:
          - 0
          - 0
        ref: thumbs_inner_cluster
      key:
        name: edge_thumb_cluster_top
    thumbs:
      anchor:
        shift:
          - 100
          - -100
      columns:
        inner:
          key:
            column_net: C5
      rows:
        cluster:
          row_net: R4

```

As you can see the `edge_thumb_cluster_top` section was moved to the top and that's causing the error.
