### ISSUE TITLE
Add concat to the preprocessor

### ISSUE THREAD

**Issue by infused-kim** [ergogen/ergogen#104]
What do you think of the idea to add concat to the ergogen preprocessor.

Perhaps something like this...
```yaml
meta:
  engine: 4.0.4
  name: 'ThinkCorney'
  version: v1-b1
  author: "@infused-kim"
  name_full: $ergogen_concat(meta.name, ' - ', meta.version)
```

Which would result in `ThinkCorney - v1-b1`.
