### ISSUE TITLE
Unexpected `bind` behavior with `asym`

### ISSUE THREAD

**Issue by ceoloide** [ergogen/ergogen#119]
When creating an asymmetric split keyboard using `mirror` and `asym: clone` to skip a single column on the left side, then creating an outline with `bound: true` and `where: true`, we get an unexpected outline on the left side, seemingly binding a non-existing point to the next key.

Here is a test case for reference:

```yaml
points:
  zones:
    matrix:
      columns:
        pinky.key:
          asym: clone
        ring:
      rows:
        home:
  mirror:
    ref: matrix_ring_home
    distance: 40
outlines:
  _keycaps:
    - what: rectangle
      where: true
      size: 18
      fillet: 1
  test:
    - what: rectangle
      where: true
      bound: true
      size: u
    - what: circle
      where: true
      radius: 1.5
      operation: stack
    - what: outline
      name: _keycaps
      operation: stack
```

And this is what the output looks like for the test outline:
![Screenshot 2024-01-22 at 9 15 36 AM](https://github.com/ergogen/ergogen/assets/60667061/511860a3-460c-42b6-af09-b29732134799)

However the expected result is this:
![Screenshot 2024-01-22 at 9 17 29 AM](https://github.com/ergogen/ergogen/assets/60667061/a717f408-8e2d-49d5-847e-af55dfbc3edd)

So it looks like Ergogen is trying to bind the `matrix_ring_home` key to the non-existing `matrix_pinky_home` one.
