### ISSUE TITLE
Setting switch footprint hotswap param to `true` reverses the order of its pins

### ISSUE THREAD

**Issue by ibrahimmkhalid** [ergogen/ergogen#120]
I was updating my board from soldered choc switches to hotswap-able choc switches and noticed that when setting the `hotswap` param to `true`, the pins of the switch also reversed. 

Here is a quick minimal example i made on [https://ergogen.cache.works/](https://ergogen.cache.works/) using mx switches

```
points:
  zones:
    matrix:
pcbs:
  board:
    footprints:
      keys:
        what: mx
        params:
          from: GND
          to: VCC
          hotswap: true
```

Changing `hotswap` to either `true` or `false` will result in the VCC and GND labels switching places. 

I believe the issue can be found on these lines, but I am not too familiar with the footprint datasheets so i am opening up this issue

https://github.com/ergogen/ergogen/blob/6079aaf332c46cc9c0dc967969be85b674b45aba/src/footprints/choc.js#L58-L75
