### ISSUE TITLE
Case generation negative extrude values cause flipped walls accross the x axis

### ISSUE THREAD

**Issue by Virginia2244** [ergogen/ergogen#121]
When I extrude something like this:
```
cases:
cases:
  case:
  - what: outline
    name: case_outer
    extrude: -2
```

I get this:
![Screenshot from 2024-02-02 20-43-26](https://github.com/ergogen/ergogen/assets/101432978/c4c98bc9-9b44-4490-8ffd-73da8573d2e8)
The top an bottom of the extrude are in the right place, however the walls are flipped around the x axis and are out of place.
