### ISSUE TITLE
Unable to change kicad layer for outlines

### ISSUE THREAD

**Issue by drelephant** [ergogen/ergogen#122]
According to the [documentation](https://docs.ergogen.xyz/pcbs/), I should be able to change what kicad layer outlines go onto.

As far as I can tell, this doesn't work (at least in Kicad v7 which I am using).

I'm using the unofficial ergogen generator at https://ergogen.cache.works/

`ergogen_layer_issue.yaml`
```
---
units:
  kx: cx
  ky: cy
points:
  zones: # define actual zones for the keys
    keymatrix:
      key:
        padding: ky
        spread: kx
      columns:
        1:
          key:
        2:
          key:
      rows:
        2:
        1:
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
pcbs:
  layerissue:
    outlines:
      raw:
        outline: raw
        layer: User.Comments
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
```
When I try to open the kicad_pcb file, I get this:
![image](https://github.com/ergogen/ergogen/assets/6712036/6fccd924-9df0-4b96-9ed3-e7b1831dc91f)

I can rescue the layer, but AFAICT it won't accept any layer, even if those layers exist in Kicad.
