### ISSUE TITLE
meta.author renders pcb to unquoted title.company

### ISSUE THREAD

**Issue by Grazfather** [ergogen/ergogen#125]
If you add a `meta.author` field with spaces, it's rendered like `(company firstname lastname)`

This is a syntax error in kicad (tested on 8). This should be quoted e.g. `(company "firstname lastname")`.

Repro:

```yaml
# https://ergogen.cache.works/
meta:
  version: 0.1.0
  author: test test
points:
  key:
  zones:
    dummy:
outlines:
  board:
    - what: rectangle

pcbs:
  keyboard:
    outlines:
      main:
        outline: board
```
