### ISSUE TITLE
Unexpected YAML properties behavior

### ISSUE THREAD

**Issue by ceoloide** [ergogen/ergogen#129]
WIth this example as context:

```yaml
points:
  key.tags: [key, key_1u]
  zones:
    matrix:
      columns:
        pinky:
          rows.top.tags: [key_1_25u]
        ring:
        middle:
        index:
        inner:
      rows:
        bottom:
        home:
        top:
outlines:
  debug:
    - what: rectangle
      where: [key]
      size: 14
    - what: rectangle
      where: [key_1u]
      size: 18
      operation: stack
    - what: rectangle
      where: [key_1_25u]
      size: [22.5, 18]
      adjust:
        shift: [-2.25,0]
      operation: stack
```

I would expect the end result for `matrix_pinky_top` to either be `tags: [key_1_25u]` or the full list: `tags: [key, key_1u, key_1_25u]`, but is instead `tags: [key_1u, key_1_25u]`:

<img width="595" alt="Screenshot 2024-04-12 at 9 36 04 AM" src="https://github.com/ergogen/ergogen/assets/60667061/852c1460-8098-4373-98a1-5bbee8b1cd83">
