### ISSUE TITLE
Using variable in points.zones.<zone_name>.columns.<col_name>.rows.mirror.width results in no image

### ISSUE THREAD

**Issue by jaybuilds222** [ergogen/ergogen#145]
This works ok when using a number in this field:
![image](https://github.com/user-attachments/assets/43fb7d92-0d96-4bc5-9b09-f49a473f8ac8)

Using a variable here results in no output:
![image](https://github.com/user-attachments/assets/a255100a-a9f2-47e0-80d0-1a8cf9e6a5c6)

**Comment by jaybuilds222** [comment]
`
points:
  zones:
    matrix:
      columns:
        outer:
          rows:
            bottom:
              width: 2U - 1.05
              mirror:
                width: 18
            home:
        pinky:
          key:
            spread: 1.5U
        ring:
        middle:
      rows:
        bottom:
        home:
  mirror:
    ref: matrix_middle_home
    distance: 50
`

**Comment by jaybuilds222** [comment]
```
points:
  zones:
    matrix:
      columns:
        outer:
          rows:
            bottom:
              width: 2U - 1.05
              mirror:
                width: 18
            home:
        pinky:
          key:
            spread: 1.5U
        ring:
        middle:
      rows:
        bottom:
        home:
  mirror:
    ref: matrix_middle_home
    distance: 50

```

**Comment by ceoloide** [comment]
Here's another simplified example:

```yaml
points:
  zones:
    matrix:
      columns:
        col:
          rows:
            row:
              width: u
              mirror.width: 2u
  mirror:
    ref: matrix_col_row
    distance: 40
```

As far as I can tell, the mirrored key doesn't have a computed width, instead it maintains it as a string. Here is a condensed `points.yaml` output:

```yaml
matrix_col_row:
  x: 0
  'y': 0
  r: 0
  meta:
    width: 19
    name: matrix_col_row
mirror_matrix_col_row:
  x: 40
  'y': 0
  r: -0.0
  meta:
    width: 2u
    name: mirror_matrix_col_row
```

My bet is that the DXF / SVG conversion fails to display the result when it encounters `width: 2u` in the mirrored key.
