### ISSUE TITLE
expand applied to the wrong shape in boolean operations on outlines

### ISSUE THREAD

**Issue by jasonobrien** [ergogen/ergogen#152]
When performing a boolean operation between two shapes in outlines (e.g. `a subtract b`), `b.expand` seems to be applied not to `b` but to `a`.

Example:

```
meta:
  engine: 4.1.0
points:
  zones:
    example.columns.pt.key.name: pt
outlines:
  combo:
    - what: rectangle
      where: pt
      size: [10, 10]
    - operation: stack
      what: circle
      where: pt
      radius: 5
```

This gives what you'd expect - a circle inscribed in a square.

![Image](https://github.com/user-attachments/assets/619448a7-c344-4980-9a53-611846409e08)

```
outlines:
  combo:
    - what: rectangle
      ...
    - operation: stack
      what: circle
      ...
      expand: 1
```

I expected the circle to get bigger - but it actually gets smaller, relative to the square.

![Image](https://github.com/user-attachments/assets/277c61ed-0814-4456-bbd2-0f8b4baa631a)
