### ISSUE TITLE
anchors at mirrored side has weird behaviour, which is even changed with `affect: xyr`

### ISSUE THREAD

**Issue by torik42** [ergogen/ergogen#33]
The configuration [anchors-of-mirrored-side.txt](https://github.com/mrzealot/ergogen/files/7145052/anchors-of-mirrored-side.txt) creates the following output:
![test_outline](https://user-images.githubusercontent.com/77811180/132884110-c86422f7-796b-49c4-a166-c534d1e8dbd4.png)

The rectangles are created with something like.
```
      - type: rectangle
        anchor:
          - ref: mirror_matrix_only_top
            affect: xyr
          - shift: [-3,-3]
            orient: 30
        size: [6,6]
```
Up to the anchors the only difference is, that `affect: xyr` is removed for the bottom keys. I would expect the behaviour from the left side also on the right (which is the mirrored one), i.e. `affect: xyr` should make no difference, but also, the upper version is the correct one.

**Comment by MvEerd** [comment]
I believe part of the issue here is that you're defining two anchors here, one of them being
```  
- ref: mirror_matrix_only_top
   affect: xyr 
``` 
the other 
```
- shift: [-3,-3]
  orient: 30
 ``` 
 
 Did you intend for the `shift` to be relative to your mirror, and be affected by your `affect` param? Then these should be under the same anchor like so
  ``` 
         anchor:
          - ref: mirror_matrix_only_top
            affect: xyr
          - shift: [-3,-3]
            orient: 30
  ``` 
  
 When `affect: xyr` is used without using 'shift' in the same anchor it will not mirror the xyval first, resulting in different behaviour.
 Perhaps `affect` should not be allowed without either `shift` or `rotate`?

**Comment by torik42** [comment]
My intention was to place a rotated rectangle in the middle of the key. Honestly, I don’t understand the relative-to-the-mirror-magic properly.
Since rectangles are placed according to their lower left corner, I needed to use orient and shift. My first guess was
```
      - type: rectangle
        anchor:
          ref: mirror_matrix_only_top
          shift: [-3,-3]
          orient: 20
        size: [6,6]
```
which works on the non-mirrored side, but not on the mirrored one:
![test_outline](https://user-images.githubusercontent.com/77811180/132892952-a0810cae-255e-461e-9dc5-bf6f92367afb.png)

For non-rotated keys, one can use
```
      - type: rectangle
        anchor:
          - ref: mirror_matrix_only_toptop
            affect: xy
          - shift: [-3,-3]
            orient: 30
        size: [6,6]
```
but I just thought, what happens with rotated keys:
![test_outline](https://user-images.githubusercontent.com/77811180/132895565-e2dcf2a7-f3e8-4978-ad04-f4c097ddeefb.png)
Added is the first row with `affect: xy` (second is `affect: xyz`, third is without) and of course the rotated keys. I don’t know how useful this all is.

As far as I now understand, if I have a ref from the mirror, then also shifts (but not rotations, nor orients?) are mirrored, such that the result looks like a mirror image. But since the placement of rectangles is also not mirrored, I need to break this mirroring. Maybe one should also mirror orients, rotations and the placement of rectangles?

**Comment by MvEerd** [comment]
How are you defining the anchors for all these?
What do you expect your example to do here?
```
      - type: rectangle
        anchor:
          - ref: mirror_matrix_only_toptop
            affect: xy
          - shift: [-3,-3]
            orient: 30
        size: [6,6]
```

Here you say, anchor this rectangle to `mirror_matrix_only_toptop`, only for x and y
and also anchor this to no ref and shift and orient it based on the default_point

Are you trying to shift and orient it based on the ref? then the `-` shouldn't be there in front of `shift`

Does this give the result you expect? 
If so I'm not sure this is a bug, but that the `x` in shift should be negated if you're anchoring it to a mirrored point?
```
      - type: rectangle
        anchor:
          - ref: mirror_matrix_only_bottom
            affect: xyr
            shift: [3,-3]
            orient: 30
        size: [6,6]
        operation: stack
      - type: rectangle
        anchor:
          - ref: mirror_matrix_only_top
            affect: xyr
            shift: [3,-3]
            orient: 30
        size: [6,6]
      - type: rectangle
        anchor:
          - ref: matrix_only_bottom
            affect: xyr
            shift: [-3,-3]
            orient: 20
        size: [6,6]
        operation: stack
      - type: rectangle
        anchor:
          - ref: matrix_only_top
            affect: xyr
            shift: [-3,-3]
            orient: 20
        size: [6,6]
        operation: stack
 ```
