### ISSUE TITLE
Unnesting does not work for outlines, if primitives are given as array.

### ISSUE THREAD

**Issue by torik42** [ergogen/ergogen#50]
The preprocessing usually takes care of unnesting `anchor.ref: <something>` into `{anchor: {ref: <something>}}`.
Moreover, one can specify outlines as objects, where each primitive gets an arbitrary name, or as arrays, where one specifies a list of primitives. The latter does not work together with unnesting. Instead, it yields the error `Error: Unexpected key "anchor.ref" within field "outlines.exports.does_not_work.0"!`. See the example below.
```yaml
points:
  zones:
    matrix:
      columns:
        col:
          rows:
            row:
outlines:
  exports:
    works1:
      - type: rectangle
        anchor:
          ref: matrix_col_row
        size: [10,10]
    works2:
      rect:
        type: rectangle
        anchor:
          ref: matrix_col_row
        size: [10,10]
    works3:
      rect:
        type: rectangle
        anchor.ref: matrix_col_row
        size: [10,10]
    does_not_work:
      - type: rectangle
        anchor.ref: matrix_col_row
        size: [10,10]
```
