### ISSUE TITLE
keys outline generation inconsistency

### ISSUE THREAD

**Issue by Woovie** [ergogen/ergogen#56]
### Description

I'm trying to use `outlines.exports` with type `keys` and I am experiencing non-generating lines or lines generating incorrectly. 

### Replication

Here is a YAML sample:

```
units:
  angle: 1
  keysize: 19.05
  
points:
  zones:
    a:
      columns:
        one:
      rows:
        one:
        two:
        three:
        four:
      rotate: angle
outlines:
  exports:
    key_outline:
      main:
        type: keys
        side: left
        size: keysize
```

Edit the `units.angle` to 2 and it will render properly. In my testing, I can only replicate in specific sizes of `units.keysize` which affects `outlines.exports.key_outline.main.size`. Various decimal values completely alters the result.

### Solution

I am unaware of one. I do not know exactly which module is causing this.
