### ISSUE TITLE
Keys outline generation failure

### ISSUE THREAD

**Issue by Woovie** [ergogen/ergogen#57]
### Description

If the `size` and `corner` values are such that the corners would generate a perfect circle, downloaded DXF only contains dot data despite clearly correct rendered view.

How it looks on ergogen.cache.works:

![image](https://user-images.githubusercontent.com/7304619/167764175-6542847a-7b95-4d49-b157-d60606c6bdb8.png)

How it looks in DWG TrueView:

![image](https://user-images.githubusercontent.com/7304619/167764257-9c9cbc23-4f89-4ad7-9c58-3a58f8dfd1e6.png)

### Replication

Use this outline export:
```yaml
outlines:
  exports:
    keys:
      main:
        type: keys
        side: left
        size: u*0.47
        corner: (u*0.47)/2
```

### Workaround

Make the corner just _slightly_ smaller:

```yaml
outlines:
  exports:
    keys:
      main:
        type: keys
        side: left
        size: u*0.47
        corner: (u*0.46)/2
```

While I do not think this is intended use, it is very useful for very specific circumstances, such as for Topre and buckling spring. I am using this for instance to draw a DXF for foam padding outline for a Model F AT.
