### ISSUE TITLE
Error: Unexpected key "stagger" within field "points.zones.matrix.columns.pinky"!

### ISSUE THREAD

**Issue by tarneaux** [ergogen/ergogen#59]
Hello,
I've tried everything to make my config file work with cli.js, but each time I get:
```
Ergogen v4.0.0-develop CLI

Interpreting format: YAML
Preprocessing input...
Calculating variables...
Parsing points...
Error: Unexpected key "stagger" within field "points.zones.matrix.columns.pinky"!
    at exports.assert (/home/max/ergogen/src/assert.js:12:15)
    at exports.unexpected (/home/max/ergogen/src/assert.js:35:9)
    at exports._render_zone (/home/max/ergogen/src/points.js:58:11)
    at exports.parse (/home/max/ergogen/src/points.js:295:26)
    at Object.process (/home/max/ergogen/src/ergogen.js:52:31)
    at /home/max/ergogen/src/cli.js:58:29
    at Object.<anonymous> (/home/max/ergogen/src/cli.js:126:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```
My config file looks like this:
```
points:
    zones:
        matrix:
            columns:
                pinky_off: null
                pinky:
                    stagger: 7
                ring:
                    stagger: 12
                middle:
                    stagger: 5
                index:
                    stagger: -6
                inner:
                    stagger: -2
                    row_overrides:
                        bottom: null
                        home: null
                        top: null
                        above: null
            rows:
                under: null
                bottom: null
                home: null
                top: null
                above: null
        thumbfan:
            anchor:
                ref: matrix_inner_bottom
                shift:
                    - 0
                    - 0
            columns:
                home:
                    spread: 21.25
                    rotate: -28
                    origin:
                        - -11.75
                        - -9
                far:
                    spread: 21.25
                    rotate: -28
                    origin:
                        - -9.5
                        - -9
            rows:
                thumb: null
        thumbfn:
            anchor:
                ref: matrix_inner_bottom
                shift:
                    - 0
                    - -70
            columns:
                thumfn: null
            rows:
                thumbfn: null
```
(copied from canonical.yaml)
What can I do? Am I missing something?
Thanks
