### ISSUE TITLE
outline.id.where does not accept a list of refs

### ISSUE THREAD

**Issue by Roming22** [ergogen/ergogen#84]
Version:  v4.0.0 at https://ergogen.cache.works

I've figured out how to draw specific keys by looking at the tests, and ended up with something like:
...
outlines:
  keycap_1u:
    - what: rectangle
      size: [1cx - 0.5, 1cy - 0.5]
      bound: false
  keycaps:
    - what: outline
      name: keycap_1u
      where:
        - ref: matrix_pinkie_home
    - what: outline
      name: keycap_1u
      where:
        - ref: matrix_pinkie_top
    - what: outline
      name: keycap_1u
      where:
        - ref: matrix_ring_home
    - what: outline
      name: keycap_1u
      where:
        - ref: matrix_ring_top
...

I would expect avoiding repetitions by using the following config, but it only draw the last element.
```
outlines:
  keycap_1u:
    - what: rectangle
      size: [1cx - 0.5, 1cy - 0.5]
      bound: false
  keycaps:
    - what: outline
      name: keycap_1u
      where:
        - ref: matrix_pinkie_home
        - ref: matrix_pinkie_top
        - ref: matrix_ring_home
        - ref: matrix_ring_top
        # Also tried - ref: [matrix_pinkie_home,matrix_pinkie_top,matrix_ring_home,matrix_ring_top]
```
