### ISSUE TITLE
Broken Templating

### ISSUE THREAD

**Issue by Narkoleptika** [ergogen/ergogen#86]
Hi I recently (perhaps ill-advisedly) switched to the development branch in my project so I could get the footprint array parameter support from b27e10374e1d59caa014763178af0ea3e36cd5d8. When I did, I noticed that templating was broken. Going through the recent commits, I've narrowed the issue down to the following change: 

```diff
-            boolean: v => v === 'true',
-            net: v => v,
-            anchor: v => v,
-            array: v => v
+            boolean: v => v === 'true'
```

from https://github.com/ergogen/ergogen/commit/c45523f38ad384e006f1f7d126c175e13716f2d4#diff-a6c84603fa491ebeb2ebb2ec5eab53e62069a455a716360df36f302c0cbabf50L200-R213

You can use this minimal config to test: 

```yaml
points:
  zones.main:
    rows.home:
    columns.home:
pcbs.minimal.footprints.choc:
  what: choc
  where: true
  params:
      from: "{{name}}"
      to: GND
```

Using the current develop branch (as of f0d22328cd155bc2938298a31aed61132ae6a523) with the minimal config to generate a PCB will yield a net of `{{name}}` instead of the expected `main_home_home`. If you then revert that change and build again, you will get the expected `main_home_home` net.
