### ISSUE TITLE
where-Negation behaves like where: True

### ISSUE THREAD

**Issue by tsteffek** [ergogen/ergogen#87]
Negation using e.g. `where: -/pinky/` does currently behave like `where: True`.

Seems to be unrelated to what actually is negated: tags, bool values, regex; all end up as `True`.

```yaml
    regex:
      - what: circle
        where: -/pinky/
        radius: 5
        operation: stack
      - what: circle
        where: /pinky/
        radius: 7
        operation: stack
```
Should result in just the bigger circles around the pinky, and smaller circles around every other point, but actually results in
![image](https://user-images.githubusercontent.com/28529410/226077029-c4c36c3a-f6c1-4181-904a-79499ed139ce.png)

<details>
  <summary>Complete Example YAML showing the Issue</summary>

```yaml
points:
  zones:
    matrix:
      columns:
        pinky:
        ring.key.stagger: 3
        middle.key.stagger: 5
        index.key.stagger: -5
        inner.key.stagger: -6
        thumb:
          key.stagger: 10
          rows:
            bottom: $unset
            top: $unset
            num: $unset
      rows:
        bottom.tags: aTag
        home:
        top:
        num:
  rotate: -10
  mirror:
    ref: matrix_thumb_home
    distance: 22
outlines:
    tagged:
      - what: rectangle
        where: aTag
        size: 14
      - what: rectangle
        where: -aTag
        size: 10
        operation: stack
    regex:
      - what: circle
        where: -/pinky/
        radius: 5
        operation: stack
      - what: circle
        where: /pinky/
        radius: 7
        operation: stack
    true:
      - what: circle
        where: True
        radius: 5
        operation: stack
      - what: circle
        where: -True
        radius: 7
        operation: stack
```
</details>
