### ISSUE TITLE
[Bug] Crash on unofficial deployment when function is used in units

### ISSUE THREAD

**Issue by tmek1244** [ergogen/ergogen#93]
**Version**: https://ergogen.cache.works/  v4.0.2 at Chrome v112.0.5615.165

**Problematic config**:
```
units:
  x: sin

points:
  zones:
    matrix:
```
It throws `unacceptable kind of an object to dump [object Function]`, so probably any other js function will cause the same (I checked min, cos, tan),

**Comment by ceoloide** [comment]
This happens because `sin` is a function so it expects a value.

The following works as expected:

```yaml
units:
  x: sin(2)

points:
  zones:
    matrix:
```

Error messages need to be cleaned up to be more explicit, for sure. Closing as stale.
