### ISSUE TITLE
`$extends` should be recursive

### ISSUE THREAD

**Issue by rschenk** [ergogen/ergogen#97]
I have been working on an ergogen cookbook with @jcmkk3's input, and one technique we agree upon is that in our configs we should prefer `$extends` to yaml &anchors when DRYing up configs. Since ergogen supports both yaml and json file formats, $extends is format-agnostic, while yaml anchors obviously don't work in json files.

The only catch is that you currently cannot nest `$extends` directives. See below.

### Nested/recursive `$extends` do not work
```yaml
# Nested $extends do not work
meta.engine: "4.0.0"

points:
  zones.matrix:
    mirror:
      ref: some_key
      distance: 4U
    key.name: some_key

  zones.moungting_hole_top:
    mirror:
      $extends: points.zones.matrix.mirror
    anchor.shift: [0, -1.25U]
    key.tags: [mounting_hole]

  zones.moungting_hole_bottom:
    $extends: points.zones.moungting_hole_top
    anchor.shift: [0, 1.25U]
```

### Nested yaml anchors do work
```yaml
# An $extends with an anchor does work
meta.engine: "4.0.0"

points:
  zones.matrix:
    mirror: &mirror
      ref: some_key
      distance: 4U
    key.name: some_key

  zones.moungting_hole_top:
    mirror: *mirror
    anchor.shift: [0, -1.25U]
    key.tags: [mounting_hole]

  zones.moungting_hole_bottom:
    $extends: points.zones.moungting_hole_top
    anchor.shift: [0, 1.25U]
```

**Comment by ceoloide** [comment]
This is being fixed as part of v4.3.0 (#160).

Using your example:

```yaml
# Nested $extends do not work
meta.engine: "4.0.0"

points:
  zones.matrix:
    mirror:
      ref: some_key
      distance: 4U
    key.name: some_key

  zones.moungting_hole_top:
    mirror:
      $extends: points.zones.matrix.mirror
    anchor.shift: [0, -1.25U]
    key.tags: [mounting_hole]

  zones.moungting_hole_bottom:
    $extends: points.zones.moungting_hole_top
    anchor.shift: [0, 1.25U]
```

You now produce the following output:

<img width="386" height="270" alt="Image" src="https://github.com/user-attachments/assets/b7d9fbd8-e645-4691-8870-e8bd81f27718" />
